name: sih_finals

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  release:
    types: [published]

jobs:
  flutter_test:
    name: Run Flutter Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: "17.x"

      - name: Set up Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze code
        run: flutter analyze

  build_appbundle:
    name: Build APK and App Bundle
    runs-on: ubuntu-latest
    needs: [flutter_test]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: "17.x"

      - name: Set up Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      - name: Clean project
        run: flutter clean

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Build App Bundle
        run: flutter build appbundle

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v3
        with:
          name: sih_finals-apk
          path: build/app/outputs/flutter-apk/app-release.apk
          retention-days: 10

      - name: Upload App Bundle Artifact
        uses: actions/upload-artifact@v3
        with:
          name: sih_finals-appbundle
          path: build/app/outputs/bundle/release/app-release.aab
          retention-days: 10

  build_ios:
    name: Build iOS and Upload IPA
    runs-on: macos-15
    needs: [flutter_test]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24'

      - name: Install dependencies
        run: |
          flutter pub get
          sudo gem install cocoapods

      - name: Update Podfile to set platform version
        run: |
          cd ios
          sed -i '' "s/# platform :ios, '9.0'/platform :ios, '13.0'/" Podfile

      - name: Set up CocoaPods
        run: |
          cd ios
          pod install

      - name: Build iOS app
        run: |
          flutter build ios --release --no-codesign
          cd build/ios/iphoneos
          mkdir -p Payload
          cp -r Runner.app Payload/
          zip -r sih_finals.ipa Payload

      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v3
        with:
          name: sih_finals-ipa
          path: build/ios/iphoneos/sih_finals.ipa
          retention-days: 10
